name: C/C++ CI

on: 
  - push
  - workflow_dispatch

defaults:
  run:
    working-directory: ./lib_jtag_core/build/linux

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
